version: '3.4'

services:
  tasky.DbMigrator:
    restart: on-failure
    image: shreegopal/dbmigrator:v1
    build:
      context: .
      dockerfile: shared/Tasky.DbMigrator/Dockerfile
    environment:
      ConnectionStrings__SaaSService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskySaaSService;Pooling=false;"
      ConnectionStrings__IdentityService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyIdentityService;Pooling=false;"
      ConnectionStrings__AdministrationService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyAdministrationService;Pooling=false;"
      ConnectionStrings__ProjectService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyProjectService;Pooling=false;"

    
  tasky.identityserver: 
    restart: on-failure
    image: shreegopal/identityserver:v1
    # build:
    #   context: .
    #   dockerfile: apps/Tasky.IdentityServer/Dockerfile
    networks:
      - traefik-public
    environment:
      App__SelfUrl: "http://3.111.38.142"
      App__ClientUrl: "http://3.111.38.142"
      App__CorsOrigins: "http://3.111.38.142"
      App__RedirectAllowedUrls: "http://3.111.38.142"
      ConnectionStrings__SaaSService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskySaaSService;Pooling=false;"
      ConnectionStrings__IdentityService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyIdentityService;Pooling=false;"
      ConnectionStrings__AdministrationService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyAdministrationService;Pooling=false;"
      ConnectionStrings__ProjectService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyProjectService;Pooling=false;"
      Redis__Configuration : "3.111.38.142:6379,password=my_master_password"
      RabbitMQ__Connections__Default__HostName : "3.111.38.142"
      RabbitMQ__Connections__EventBus__ClientName : "TaskyIdentityService"
      RabbitMQ__Connections__EventBus__ExchangeName : "Tasky"
      Serilog__WriteTo__[0]__Name : "Seq"
      # Serilog__WriteTo__[0]__Args__serverUrl : "https://seq.youtube.antosubash.com"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.identityserver.rule=Host(`3.111.38.142`)"
        - "traefik.http.services.identityserver.loadbalancer.server.port=80"
        - "traefik.http.routers.identityserver.entrypoints=websecure"
        - "traefik.http.routers.identityserver.tls=true"
        - "traefik.http.routers.identityserver.tls.certresolver=leresolver"
      

  tasky.gateway:
    restart: on-failure
    image: shreegopal/gateway:v1
    # build:
    #   context: .
    #   dockerfile: gateway/Tasky.Gateway/Dockerfile
    networks:
      - traefik-public
    environment:
      ReverseProxy__Clusters__main__Destinations__main__Address : "http://3.111.38.142:7001"
      ReverseProxy__Clusters__identity__Destinations__identity__Address : "http://3.111.38.142:7002"
      ReverseProxy__Clusters__account__Destinations__account__Address : "http://3.111.38.142:7002"
      ReverseProxy__Clusters__saas__Destinations__saas__Address : "http://3.111.38.142:7003"
      ReverseProxy__Clusters__project__Destinations__project__Address : "http://3.111.38.142:7004"
      Serilog__WriteTo__[0]__Name : "Seq"
      # Serilog__WriteTo__[0]__Args__serverUrl : "https://seq.youtube.antosubash.com"
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway.rule=Host(`3.111.38.142`)"
        - "traefik.http.services.gateway.loadbalancer.server.port=80"
        - "traefik.http.routers.gateway.entrypoints=websecure"
        - "traefik.http.routers.gateway.tls=true"
        - "traefik.http.routers.gateway.tls.certresolver=leresolver"



  tasky.administrationservice.httpapi.host:
    restart: on-failure
    image: shreegopal/administrationservice:v1
    # build:
    #   context: .
    #   dockerfile: services/administration/host/Tasky.AdministrationService.HttpApi.Host/Dockerfile
    ports:
      - target: 80
        published: 7001
        protocol: tcp
        mode: host
    environment:
      App__CorsOrigins: http://3.111.38.142:7000
      ConnectionStrings__SaaSService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskySaaSService;Pooling=false;"
      ConnectionStrings__IdentityService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyIdentityService;Pooling=false;"
      ConnectionStrings__AdministrationService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyAdministrationService;Pooling=false;"
      ConnectionStrings__ProjectService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyProjectService;Pooling=false;"
      Redis__Configuration : "3.111.38.142:6379,password=my_master_password"
      AuthServer__Authority : "http://3.111.38.142"
      AuthServer__RequireHttpsMetadata : "false"
      AuthServer__SwaggerClientId : "AdministrationService_Swagger"
      AuthServer__SwaggerClientSecret : "1q2w3e*"
      RabbitMQ__Connections__Default__HostName : "3.111.38.142"
      RabbitMQ__Connections__EventBus__ClientName : "TaskyAdministrationService"
      RabbitMQ__Connections__EventBus__ExchangeName : "Tasky"
      Serilog__WriteTo__[0]__Name : "Seq"
      # Serilog__WriteTo__[0]__Args__serverUrl : "https://seq.youtube.antosubash.com"



  tasky.identityservice.httpapi.host:
    restart: on-failure
    image: shreegopal/identityservice:v1
    # build:
    #   context: .
    #   dockerfile: services/identity/host/Tasky.IdentityService.HttpApi.Host/Dockerfile
    ports:
      - target: 80
        published: 7002
        protocol: tcp
        mode: host
    environment:
      App__CorsOrigins: http://3.111.38.142:7000
      ConnectionStrings__SaaSService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskySaaSService;Pooling=false;"
      ConnectionStrings__IdentityService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyIdentityService;Pooling=false;"
      ConnectionStrings__AdministrationService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyAdministrationService;Pooling=false;"
      ConnectionStrings__ProjectService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyProjectService;Pooling=false;"
      Redis__Configuration : "3.111.38.142:6379,password=my_master_password"
      AuthServer__Authority : "http://3.111.38.142"
      AuthServer__RequireHttpsMetadata : "false"
      AuthServer__SwaggerClientId : "IdentityService_Swagger"
      AuthServer__SwaggerClientSecret : "1q2w3e*"
      RabbitMQ__Connections__Default__HostName : "3.111.38.142"
      RabbitMQ__Connections__EventBus__ClientName : "TaskyIdentityService"
      RabbitMQ__Connections__EventBus__ExchangeName : "Tasky"
      Serilog__WriteTo__[0]__Name : "Seq"
      # Serilog__WriteTo__[0]__Args__serverUrl : "https://seq.youtube.antosubash.com"

      


  tasky.projectservice.httpapi.host:
    restart: on-failure
    image: shreegopal/projectservice:v1
    # build:
    #   context: .
    #   dockerfile: services/project/host/Tasky.ProjectService.HttpApi.Host/Dockerfile
    ports:
      - target: 80
        published: 7004
        protocol: tcp
        mode: host
    environment:
      App__CorsOrigins: http://3.111.38.142:7000
      ConnectionStrings__SaaSService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskySaaSService;Pooling=false;"
      ConnectionStrings__IdentityService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyIdentityService;Pooling=false;"
      ConnectionStrings__AdministrationService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyAdministrationService;Pooling=false;"
      ConnectionStrings__ProjectService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyProjectService;Pooling=false;"
      Redis__Configuration : "3.111.38.142:6379,password=my_master_password"
      AuthServer__Authority : "http://3.111.38.142"
      AuthServer__RequireHttpsMetadata : "false"
      AuthServer__SwaggerClientId : "IdentityService_Swagger"
      AuthServer__SwaggerClientSecret : "1q2w3e*"
      RabbitMQ__Connections__Default__HostName : "3.111.38.142"
      RabbitMQ__Connections__EventBus__ClientName : "TaskyIdentityService"
      RabbitMQ__Connections__EventBus__ExchangeName : "Tasky"
      Serilog__WriteTo__[0]__Name : "Seq"
      # Serilog__WriteTo__[0]__Args__serverUrl : "https://seq.youtube.antosubash.com"


  tasky.saasservice.httpapi.host:
    restart: on-failure
    image: shreegopal/saasservice:v1
    mem_limit: 2g 
    # build:
    #   context: .
    #   dockerfile: services/saas/host/Tasky.SaaSService.HttpApi.Host/Dockerfile      
    ports:
      - target: 80
        published: 7003
        protocol: tcp
        mode: host
    environment:
      App__CorsOrigins: http://3.111.38.142:7000
      ConnectionStrings__SaaSService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskySaaSService;Pooling=false;"
      ConnectionStrings__IdentityService: "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyIdentityService;Pooling=false;"
      ConnectionStrings__AdministrationService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyAdministrationService;Pooling=false;"
      ConnectionStrings__ProjectService : "User ID=postgres;Password=my_postgres_password;Host=10.0.0.2;Port=5432;Database=TaskyProjectService;Pooling=false;"
      Redis__Configuration : "3.111.38.142:6379,password=my_master_password"
      AuthServer__Authority : "http://3.111.38.142"
      AuthServer__RequireHttpsMetadata : "false"
      AuthServer__SwaggerClientId : "IdentityService_Swagger"
      AuthServer__SwaggerClientSecret : "1q2w3e*"
      RabbitMQ__Connections__Default__HostName : "3.111.38.142"
      RabbitMQ__Connections__EventBus__ClientName : "TaskyIdentityService"
      RabbitMQ__Connections__EventBus__ExchangeName : "Tasky"
      Serilog__WriteTo__[0]__Name : "Seq"
      # Serilog__WriteTo__[0]__Args__serverUrl : "https://seq.youtube.antosubash.com"

    
networks:
  traefik-public:
    external: true